#pragma once
// Win/draw/loss display (UCI_ShowWDL).
//
// A reported score v (internal centipawns, side to move) is turned into per-mille chances with a
// logistic model whose centre and width depend on the material on the board:
//
//     W = 1 / (1 + exp((a - v) / b))      L = 1 / (1 + exp((a + v) / b))      D = 1 - W - L
//
// a is the score at which a win becomes as likely as not, b how quickly the result sharpens around it;
// both are cubics in x = clamp(material, lo, hi) / 58, material = P + 3N + 3B + 5R + 9Q over both sides.
// The coefficients (src/wdl_model.hpp) are generated by train/fit_wdl.py from the engine's own
// self-play and belong to the shipped network; another EvalFile is not calibrated by them.
//
// Display only: nothing here feeds the search, and the reported cp stays the raw internal score.
// Mates, tablebase results and 50-move-downgraded mates are decisive (1000 0 0 / 0 0 1000).
#include <algorithm>
#include <cmath>

#include "types.hpp"
#include "wdl_model.hpp"

namespace engine {

struct WdlPermille {
    int win, draw, loss;   // side to move, per mille, sum 1000
};

// Lowest decisive magnitude: tablebase wins reach down to VALUE_TB_WIN_IN_MAX_PLY - MAX_PLY, and
// every mate score and 50-move-downgraded mate lies above it.
inline constexpr Value kWdlDecisive = VALUE_TB_WIN_IN_MAX_PLY - MAX_PLY;

// P1 N3 B3 R5 Q9 over both sides, kings excluded.
[[nodiscard]] inline int wdl_material(const Board& b) noexcept {
    return b.pieces(PieceType::PAWN).count() + 3 * b.pieces(PieceType::KNIGHT).count() +
           3 * b.pieces(PieceType::BISHOP).count() + 5 * b.pieces(PieceType::ROOK).count() +
           9 * b.pieces(PieceType::QUEEN).count();
}

namespace wdl_detail {
constexpr double horner(const double (&c)[4], double x) noexcept { return ((c[0] * x + c[1]) * x + c[2]) * x + c[3]; }
constexpr double x_of(int material) noexcept {
    return std::clamp(material, wdl_model::kMaterialLo, wdl_model::kMaterialHi) / wdl_model::kMaterialAnchor;
}
// a > 0 and b > 0 keep D >= 0 (W + L <= 1 exactly when a / b >= 0).
constexpr bool model_positive() noexcept {
    for (int m = wdl_model::kMaterialLo; m <= wdl_model::kMaterialHi; ++m)
        if (!(horner(wdl_model::kA, x_of(m)) > 0.0 && horner(wdl_model::kB, x_of(m)) > 0.0)) return false;
    return true;
}
}  // namespace wdl_detail

static_assert(wdl_detail::model_positive(), "wdl_model.hpp: a(m) and b(m) must be positive on the clamp range");

[[nodiscard]] constexpr WdlPermille wdl_from_value(Value v, int material) noexcept {
    if (v >= kWdlDecisive) return {1000, 0, 0};
    if (v <= -kWdlDecisive) return {0, 0, 1000};
    const double x = wdl_detail::x_of(material);
    const double a = wdl_detail::horner(wdl_model::kA, x);
    const double b = wdl_detail::horner(wdl_model::kB, x);
    int w = static_cast<int>(0.5 + 1000.0 / (1.0 + std::exp((a - v) / b)));
    int l = static_cast<int>(0.5 + 1000.0 / (1.0 + std::exp((a + v) / b)));
    if (w + l > 1000) {   // per-mille rounding can overshoot by one: keep D >= 0
        if (w >= l) w = 1000 - l;
        else l = 1000 - w;
    }
    return {w, 1000 - w - l, l};
}

static_assert(wdl_from_value(VALUE_MATE - 1, 40).win == 1000 && wdl_from_value(-(VALUE_MATE - 1), 40).loss == 1000);
static_assert(wdl_from_value(kWdlDecisive, 0).win == 1000 && wdl_from_value(-kWdlDecisive, 90).loss == 1000);
static_assert(wdl_from_value(VALUE_TB_WIN_IN_MAX_PLY - 1, 78).win == 1000);   // a 50-move-downgraded mate

}  // namespace engine
