// src/wdl_model.hpp -- GENERATED by train/fit_wdl.py; do not edit by hand (re-fit: see that script).
// Win-rate model for UCI_ShowWDL (src/wdl.hpp), fitted on the engine's own self-play:
//   data     pool_v28.data (2,341,058,606 records); search scores and game results, mates excluded
//   fit      2,048,397,419 train / 227,623,932 holdout positions (holdout = board hash % 10)
//   model    W = 1/(1+exp((a-v)/b)), L = 1/(1+exp((a+v)/b)), D = 1-W-L; a, b cubic in clamp(material)/58,
//            material = P+3N+3B+5R+9Q over both sides, clamp [4, 78]
//   holdout  0.690616 nats/position (constant a, b: 0.738145; score-blind: 1.094118)
//   fitted   2026-09-27 for nets/SCNNUEv3-2026-09-26.scn5 -- re-fit when the net changes
#pragma once

namespace engine::wdl_model {

inline constexpr int    kMaterialLo     = 4;
inline constexpr int    kMaterialHi     = 78;
inline constexpr double kMaterialAnchor = 58.0;
// a(x) = ((kA[0]*x + kA[1])*x + kA[2])*x + kA[3], x = clamp(material, kMaterialLo, kMaterialHi) / kMaterialAnchor
inline constexpr double kA[4] = {-602.29325026208141, 1858.23363461079, -2062.6568354352189, 1042.6946879849979};
inline constexpr double kB[4] = {-78.966734239251963, 155.06301674953423, -77.721948458750447, 314.65475241074807};

}  // namespace engine::wdl_model
